services:
  - type: web
    name: face-recognition-attendance
    env: docker # Changed from 'python' to 'docker'
    region: frankfurt # You can change this to your preferred region
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: "3306"
